<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<artifactId>sys-service</artifactId>
		<groupId>com.ershiyi</groupId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>
	<groupId>com.ershiyi</groupId>
	<artifactId>sys-service-provider</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.ershiyi</groupId>
			<artifactId>auto-service-api</artifactId>
			<version>${platform.api.auto.version}</version>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.46</version>
		</dependency>
		<dependency>
			<groupId>com.ershiyi</groupId>
			<artifactId>common-core</artifactId>
			<version>${platform.common.version}</version>
		</dependency>

		<dependency>
			<groupId>com.ershiyi</groupId>
			<artifactId>orm-starter</artifactId>
			<version>${platform.orm.version}</version>
		</dependency>

		<dependency>
			<groupId>com.ershiyi</groupId>
			<artifactId>web-starter</artifactId>
			<version>${platform.web.version}</version>
		</dependency>

		<dependency>
			<groupId>com.ershiyi</groupId>
			<artifactId>sys-domain</artifactId>
			<version>${platform.domain.sys.version}</version>
		</dependency>

		<dependency>
			<groupId>com.ershiyi</groupId>
			<artifactId>sys-mapper</artifactId>
			<version>${platform.mapper.sys.version}</version>
		</dependency>


		<dependency>
			<groupId>com.ershiyi</groupId>
			<artifactId>student-app-domain</artifactId>
			<version>${platform.domain.student-app.version}</version>
		</dependency>

		<dependency>
			<groupId>com.ershiyi</groupId>
			<artifactId>sys-service-api</artifactId>
			<version>${platform.api.sys.version}</version>
		</dependency>


		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
    </dependencies>

	<build>
		<!-- 打包名称 -->
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring-boot.version}</version>
				<executions>
					<execution>
						<goals>
							<goal>repackage</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<configuration>
					<nonFilteredFileExtensions>
						<nonFilteredFileExtension>db</nonFilteredFileExtension>
					</nonFilteredFileExtensions>
				</configuration>
			</plugin>

			<!--maven deploy 忽略发布插件-->
			<!--<plugin>-->
				<!--<groupId>org.apache.maven.plugins</groupId>-->
				<!--<artifactId>maven-deploy-plugin</artifactId>-->
				<!--<version>${maven-deploy-plugin.version}</version>-->
				<!--<configuration>-->
					<!--<skip>true</skip>-->
				<!--</configuration>-->
			<!--</plugin>-->
			<!--<plugin>-->
				<!--&lt;!&ndash;打包跳过测试&ndash;&gt;-->
				<!--<groupId>org.apache.maven.plugins</groupId>-->
				<!--<artifactId>maven-surefire-plugin</artifactId>-->
				<!--<version>2.22.1</version>-->
				<!--<configuration>-->
					<!--<skipTests>true</skipTests>-->
				<!--</configuration>-->
			<!--</plugin>-->
			<!--<plugin>-->
				<!--<groupId>com.spotify</groupId>-->
				<!--<artifactId>docker-maven-plugin</artifactId>-->
				<!--<version>${maven-docker-plugin.version}</version>-->
				<!--&lt;!&ndash;将插件绑定在某个phase执行&ndash;&gt;-->
				<!--<executions>-->
					<!--<execution>-->
						<!--<id>build-image</id>-->
						<!--&lt;!&ndash;将插件绑定在package这个phase上。也就是说，用户只需执行mvn package ，就会自动执行mvn docker:build&ndash;&gt;-->
						<!--<phase>package</phase>-->
						<!--<goals>-->
							<!--<goal>build</goal>-->
						<!--</goals>-->
					<!--</execution>-->
				<!--</executions>-->
				<!--<configuration>-->
					<!--&lt;!&ndash;指定生成的镜像名&ndash;&gt;-->
					<!--<imageName>${docker.image.prefix}/${project.artifactId}</imageName>-->
					<!--&lt;!&ndash;指定标签&ndash;&gt;-->
					<!--<imageTags>-->
						<!--<imageTag>latest</imageTag>-->
					<!--</imageTags>-->
					<!--&lt;!&ndash; 指定 Dockerfile 路径 ${project.basedir}：项目根路径下&ndash;&gt;-->
					<!--<dockerDirectory>${project.basedir}</dockerDirectory>-->
					<!--&lt;!&ndash;指定远程 docker api地址&ndash;&gt;-->
					<!--<dockerHost>${docker.host}</dockerHost>-->

					<!--<buildArgs>-->
						<!--<JAR_FILE>target/${project.build.finalName}.jar</JAR_FILE>-->
					<!--</buildArgs>-->
					<!--&lt;!&ndash; 这里是复制 jar 包到 docker 容器指定目录配置 &ndash;&gt;-->
					<!--<dockerCertPath> ${docker.create}</dockerCertPath>-->
					<!--<resources>-->
						<!--<resource>-->
							<!--<targetPath>/ROOT</targetPath>-->
							<!--&lt;!&ndash;jar 包所在的路径 此处配置的 即对应 target 目录&ndash;&gt;-->
							<!--<directory>${project.build.directory}</directory>-->
							<!--&lt;!&ndash; 需要包含的 jar包 ，这里对应的是 Dockerfile中添加的文件名　&ndash;&gt;-->
							<!--<include>${project.build.finalName}.jar</include>-->
						<!--</resource>-->
					<!--</resources>-->
				<!--</configuration>-->

			<!--</plugin>-->
		</plugins>
	</build>
</project>
