<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.ershiyi</groupId>
    <artifactId>platform</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>platform-commons</module>
        <module>platform-services</module>
        <module>platform-domain</module>
        <module>platform-mapper</module>
        <!--<module>platform-database</module>-->
        <module>platform-gateway</module>
        <module>paltform-dependencies</module>
    </modules>

    <properties>
        <java.version>1.8</java.version>
        <!--项目统一字符集编码-->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <platform.common.version>1.0.0-SNAPSHOT</platform.common.version>
        <platform.web.version>1.0.0-SNAPSHOT</platform.web.version>
        <platform.orm.version>1.0.0-SNAPSHOT</platform.orm.version>

        <platform.api.issue-inspect.version>1.0.0-SNAPSHOT</platform.api.issue-inspect.version>
        <platform.domain.issue-inspect.version>1.0.0-SNAPSHOT</platform.domain.issue-inspect.version>
        <platform.mapper.issue-inspect.version>1.0.0-SNAPSHOT</platform.mapper.issue-inspect.version>

        <platform.api.parent-web.version>1.0.0-SNAPSHOT</platform.api.parent-web.version>
        <platform.domain.parent-web.version>1.0.0-SNAPSHOT</platform.domain.parent-web.version>
        <platform.mapper.parent-web.version>1.0.0-SNAPSHOT</platform.mapper.parent-web.version>

        <platform.api.student-app.version>1.0.0-SNAPSHOT</platform.api.student-app.version>
        <platform.domain.student-app.version>1.0.0-SNAPSHOT</platform.domain.student-app.version>
        <platform.mapper.student-app.version>1.0.0-SNAPSHOT</platform.mapper.student-app.version>
        <platform.pay.service.version>1.0.0-SNAPSHOT</platform.pay.service.version>
        <platform.api.teacher-web.version>1.0.0-SNAPSHOT</platform.api.teacher-web.version>
        <platform.domain.teacher-web.version>1.0.0-SNAPSHOT</platform.domain.teacher-web.version>
        <platform.mapper.teacher-web.version>1.0.0-SNAPSHOT</platform.mapper.teacher-web.version>
        <platform.domain.pay.version>1.0.0-SNAPSHOT</platform.domain.pay.version>
        <platform.api.auto.version>1.0.0-SNAPSHOT</platform.api.auto.version>
        <platform.domain.auto.version>1.0.0-SNAPSHOT</platform.domain.auto.version>
        <platform.mapper.auto.version>1.0.0-SNAPSHOT</platform.mapper.auto.version>


        <platform.api.resources.version>1.0.0-SNAPSHOT</platform.api.resources.version>
        <platform.domain.resources.version>1.0.0-SNAPSHOT</platform.domain.resources.version>
        <platform.mapper.resources.version>1.0.0-SNAPSHOT</platform.mapper.resources.version>

        <platform.api.sys.version>1.0.0-SNAPSHOT</platform.api.sys.version>
        <platform.domain.sys.version>1.0.0-SNAPSHOT</platform.domain.sys.version>
        <platform.mapper.sys.version>1.0.0-SNAPSHOT</platform.mapper.sys.version>
        <platform.mapper.pay.version>1.0.0-SNAPSHOT</platform.mapper.pay.version>



        <platform.api.common.version>1.0.0-SNAPSHOT</platform.api.common.version>
        <platform.domain.common.version>1.0.0-SNAPSHOT</platform.domain.common.version>
        <platform.mapper.common.version>1.0.0-SNAPSHOT</platform.mapper.common.version>

        <!--<platform.api.case.version>1.0.0-SNAPSHOT</platform.api.case.version>-->
        <!--<platform.domain.case.version>1.0.0-SNAPSHOT</platform.domain.case.version>-->
        <!--<platform.mapper.case.version>1.0.0-SNAPSHOT</platform.mapper.case.version>-->

        <!--<platform.api.medical.version>1.0.0-SNAPSHOT</platform.api.medical.version>-->
        <!--<platform.domain.medical.version>1.0.0-SNAPSHOT</platform.domain.medical.version>-->
        <!--<platform.mapper.medical.version>1.0.0-SNAPSHOT</platform.mapper.medical.version>-->

        <!--<platform.api.reservationplatform.version>1.0.0-SNAPSHOT</platform.api.reservationplatform.version>-->
        <!--<platform.domain.reservationplatform.version>1.0.0-SNAPSHOT</platform.domain.reservationplatform.version>-->
        <!--<platform.mapper.reservationplatform.version>1.0.0-SNAPSHOT</platform.mapper.reservationplatform.version>-->

        <!--<platform.api.finance.version>1.0.0-SNAPSHOT</platform.api.finance.version>-->
        <!--<platform.domain.finance.version>1.0.0-SNAPSHOT</platform.domain.finance.version>-->
        <!--<platform.mapper.finance.version>1.0.0-SNAPSHOT</platform.mapper.finance.version>-->


        <!--<platform.api.supervisor-inspect.version>1.0.0-SNAPSHOT</platform.api.supervisor-inspect.version>-->
        <!--<platform.domain.supervisor-inspect.version>1.0.0-SNAPSHOT</platform.domain.supervisor-inspect.version>-->
        <!--<platform.mapper.supervisor-inspect.version>1.0.0-SNAPSHOT</platform.mapper.supervisor-inspect.version>-->


        <!--<platform.api.risk.version>1.0.0-SNAPSHOT</platform.api.risk.version>-->
        <!--<platform.domain.risk.version>1.0.0-SNAPSHOT</platform.domain.risk.version>-->
        <!--<platform.mapper.risk.version>1.0.0-SNAPSHOT</platform.mapper.risk.version>-->


        <!-- 打包 -->
        <spring-boot.version>2.2.5.RELEASE</spring-boot.version>
        <maven-deploy-plugin.version>2.8.2</maven-deploy-plugin.version>
        <maven-dockerfile-plugin.version>1.4.10</maven-dockerfile-plugin.version>
        <maven-docker-plugin.version>1.0.0</maven-docker-plugin.version>
    </properties>

    <!-- 环境 -->
    <profiles>
        <!-- 开发 -->
        <profile>
            <id>dev</id>
            <activation>
                <!--默认激活配置-->
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <!--当前环境-->
                <profile.name>dev</profile.name>
                <!--Nacos配置中心地址-->
                <config.server-addr>localhost:8848</config.server-addr>
                <!--Nacos配置中心命名空间,用于支持多环境.这里必须使用ID，不能使用名称,默认为空-->
                <config.namespace></config.namespace>
                <!--Nacos服务发现地址-->
                <discovery.server-addr>localhost:8848</discovery.server-addr>
                <docker.image.prefix>ershiyi</docker.image.prefix>
                <docker.host>http://192.168.3.17:2375</docker.host>
            </properties>
        </profile>
        <!-- 生产 -->
        <profile>
            <id>online</id>
            <properties>
                <!--当前环境,生产环境为空-->
                <profile.name>online</profile.name>
                <!--Nacos配置中心地址-->
                <config.server-addr>192.168.1.13:8848</config.server-addr>
                <!--Nacos配置中心命名空间,用于支持多环境.这里必须使用ID，不能使用名称,默认为空-->
                <config.namespace></config.namespace>
                <!--Nacos服务发现地址-->
                <discovery.server-addr>192.168.1.13:8848</discovery.server-addr>
                <docker.image.prefix>ershiyi</docker.image.prefix>
                <docker.host>http://218.76.32.241:2376</docker.host>
                <docker.create>D:\docker\ca-106</docker.create>
            </properties>
        </profile>
    </profiles>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.ershiyi</groupId>
                <artifactId>platform-dependencies</artifactId>
                <version>1.0.0-SNAPSHOT</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <resources>
            <!-- 先指定 src/main/resources下所有文件及文件夹为资源文件 -->
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>**/*</include>
                </includes>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.1.0</version>
            </plugin>
            <plugin>
                <!--打包跳过测试-->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>ali-maven</id>
            <url>http://maven.aliyun.com/nexus/content/groups/public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
                <checksumPolicy>fail</checksumPolicy>
            </snapshots>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/libs-milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>
