#���Ի�����ʮһСʱ���� ==> ΢��
#΢��ͳһ֧����ַ
wechat.unifiedorder.url=https://api.mch.weixin.qq.com/pay/unifiedorder
#���ں�ƽ̨Appid
wechat.appid=wx1d7758783b3ba004
#���ں�ƽ̨��Կ
wechat.appsecret=2069126388c0d1352ee1ea3bc5ce1c3c
#�̻�ƽ̨�̻���
wechat.mchid=1602975534
#�̻�ƽ̨��ԿID
wechat.wechatkey=qazwsxedcrfvtgbyhnujmikolpqazwsx
#body
wechat.body=JIAOYU
#΢��֧������
wechat.type=JSAPI
#��ȡ��Ȩ�û���Ϣ��ַ
wechat.oatuh.getUserInfoUrl=http://tdmdjb.natappfree.cc/wechat/getUserInfo
#�ص���ַ
wechat.notify.url=http://pay.21hourspushl.com/wechat/whechatPayNotify
#΢���ض����ַ
wechat.redirect.url=


#֧�������Ի�������
#֧��������
#alipay.gateway=https://openapi.alipay.com/gateway.do
##�̻�appid
#alipay.appid=2021001193605748
##˽Կ pkcs8��ʽ��
#alipay.ras.private.key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC0ojWEKGWy6Zun04O6A9cdpj4UAo0viZu4fUlLGjOOiVtCyojfkgVlyWjEGQzhyxXIJVLEf3HNjrGJZTpBNIefOKbo2D7gZCKckvluLWOI6SPxq8fvyk3bdvipKDLhfjkMO4xdYbbtJmfVBmmXb++rDn5aWImAgP8UQtwwdMuS+20lPyKq0R7ERgilP59umtEychXHPhbUhmWf0WAqsEuoY3BFX+gTIC+G05QrB2co/enpa4bNTtSK5ZRlOQYEZbWkOmEv6XxkncePdgLh/y8Omx46FdO3pptZbD/6CRl2eL+opAy53XRTv5JNTvLvulRsYJH5L4I9TNQgpNB1jh95AgMBAAECggEBAKs9j4BfD7Jh1kdutFU26MrZ28X6eUAUs0RduYryJug8fQC/oqxX8LgDDUfB+71eWqLoByPzMb7ORK5dAbHpC509BrZ8snblVw6aIs55Rv/3DTVBRYSkg9THX4p1am7sy0Y2eaXZSaJeo1aHArkmy82dKtmZT5k8MRVTIQzq3EbUbfKKGT6in7UM8V5xVTRxAvtDxALYdiPQntcEO0fEg2j/Bnt3Z7Ep/qCr3NJAAN+ten2GmIyDht67quQn8fOgowlwhV3xuhCt9FcHh2nrT4o73fWs20P4rGVpYdHTgQj7mId6s3At55WRWSD0mxUh8/QKHoA/Ae9dDIMNMlBI6pECgYEA4iESU8GiVGGaLsTsobpIkjT7AbFesHqHHQiTw20oO2O2NtE3/2O1JCTE0k9MAMldYR9ZnyMxghz15PtvN3FB/p5K2tBGiKbpgTf8+8VC7pl0iEgKr0Vkth1DM8BGEKx8INe7Y5uvT98hfZVJpQkc9kTzzDXQUXU4WqbS41OW1CUCgYEAzH6hec7ZdnLrccvG1LklO3+57GxqtV5THZ/HKQNdqtuIeeh13xlECoLI0IbVtm902TmMcWYNb6A9oR2wL3tCT4u4dKyeYeqTb0Qi0EeKMc6hAgTOAvCAElhuhZjWA4RWCU4M41YbFyLiZTCtViJ0vE+GX/QPq0gCCCeSn0dbs8UCgYB9z+axgQd/KTqukNQTe2CLMD0DiRrk15c7GR2VWrNKr8SepTMhvej3rhlv5bykp2Rz+AxWFS+jc9d/ykDruPD96DY/nifQOgWq5mqz7eG6fNiwRlzjfZl2FbvhHDYfasg5Qa450lHs/3lTtO7fir15a421ba900uJC1ZR59HTznQKBgQCscwFzekeTBvicX29Ohs/qLB07TnZyepf2/H30jT0ZT8b4n1t/h4wEnSQCDiL9lWJhqZFRM/GSt/wg+atRb02NTVOBOOzbv/kTNM9y+1GEDS9kR27/tZcbYW3axfd8wcXYVPSzZjK0QRvQn8sdPzNYdmvoUSZBmBj2jYCtR30CzQKBgGhPgJigzuPiO2myyqdLBJAH6g9Bmfcw5Wl78UqYtLk1u5SmfeK748h/Yfa+w0YuDLPOfK22Kka/GQstBtSgZ8QJ+50Nj+QPQXTFdx4Piv3P5i4qV9DR/jqF6FWG/TGkcvFYedPKNzC/QQMOHvIIxzvBX16psMIfW1dSA8YxD9PI
##�ص���ַ
##alipay.notify.url=http://pay.21hourspushl.com/alipay/alipayOrderNotify
#alipay.notify.url=http://vq6sh4.natappfree.cc/alipay/alipayOrderNotify
##֧���ɹ���ת��ַ
#alipay.return.url=
##�ַ������ʽ
#alipay.charset=UTF-8
##֧������Կ
#alipay.alipaypublic.key=GMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKI1hChlsumbp9ODugPXHaY+FAKNL4mbuH1JSxozjolbQsqI35IFZcloxBkM4csVyCVSxH9xzY6xiWU6QTSHnzim6Ng+4GQinJL5bi1jiOkj8avH78pN23b4qSgy4X45DDuMXWG27SZn1QZpl2/vqw5+WliJgID/FELcMHTLkvttJT8iqtEexEYIpT+fbprRMnIVxz4W1IZln9FgKrBLqGNwRV/oEyAvhtOUKwdnKP3p6WuGzU7UiuWUZTkGBGW1pDphL+l8ZJ3Hj3YC4f8vDpseOhXTt6abWWw/+gkZdni/qKQMud10U7+STU7y77pUbGCR+S+CPUzUIKTQdY4feQIDAQAB
##Ӧ�ù�Կ               MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKI1hChlsumbp9ODugPXHaY+FAKNL4mbuH1JSxozjolbQsqI35IFZcloxBkM4csVyCVSxH9xzY6xiWU6QTSHnzim6Ng+4GQinJL5bi1jiOkj8avH78pN23b4qSgy4X45DDuMXWG27SZn1QZpl2/vqw5+WliJgID/FELcMHTLkvttJT8iqtEexEYIpT+fbprRMnIVxz4W1IZln9FgKrBLqGNwRV/oEyAvhtOUKwdnKP3p6WuGzU7UiuWUZTkGBGW1pDphL+l8ZJ3Hj3YC4f8vDpseOhXTt6abWWw/+gkZdni/qKQMud10U7+STU7y77pUbGCR+S+CPUzUIKTQdY4feQIDAQAB
#alipay.public.key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvAM4sRSf3P6AYTfBKjn8/sOucXQ61hloOYUOJxrl5fppeckYJPvXOBOHAZvuVApZNkDjZ7MT6BtncN8y/pcdPsg07M9epATiyummdmxPrRhCjCjYtN9saF5ozMnd3TFtJZqqN4HO6AdEtD1AQVSvuiKGS8nUtAz7dvJphzGNhyaRjbaV14XNLFwTm98rIToT4iBUvTW/ri4XPdsQHeLXyOBdXOOAs9UbqU9+fJR49FF2iiPSNPJXm15GBojCa1rpwOgkeBm5sBsW0JpaWpnzJj1isjgAo67080nMwI/zsusSAgh1zra9zT9APz/34KGEj658DP7T69Jf94DWachCcQIDAQAB
#
#alipay.payer.show.name=��ʮһСʱ
#alipay.remark=���϶�ʮһСʱ��ֵ
#alipay.payee.type=ALIPAY_LOGONI吧

#学生端
alipay.appid =2021002128646639
alipay.gateway =https://openapi.alipay.com/gateway.do
#alipay.ras.private.key =MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDLxE9azbk2JymMrSrkMKoBOeaSqt2C8LyOA9xqNHDPB+liUA4FVMJRGaRXAcFdPtYlFIeyuYKiKM9fvD4m1wDBHVWOtiMcCH1RNtD1VB/myeJf78n62Pbc613ZvjPiUOiDrUVctznCW7TLYI6xshacusgDXeo9XJzv/yqwqSuahF3Qm6CBzzL+0n6WO4SfOywiBLi6q8u1FfkBRyxUKoADQZX/dTfmGYsvd/BWh0ErI7wEB70YJXfhRmRwK/fJlkz4JWjggkew/eXu7vkBuOa3/xM9Ppe7nK+swC3lBQJIH+W7lMC7Q7uN1d5XY6IGBq1DJ6+APHvU0/Y7mvM4aOPrAgMBAAECggEARftJ9bmp3ntcvb/Ld0tvV7R3B/A+23WqjGuvC5qvE6t38BfmeNY/VnMkCe3EZy3phhqi8DLeNqslbY/NGLHGxIw6kiTjsgEIaRgWc+tMeYrkgGZuTASv4/fB58J3N0bqVC7yH4GeCK5OTXsABu9O7M0JXH6osCJak+Ji2wF+xDYMn5nynPhCZzpx8PMmuc6MM+U7pDPyC01ENWpkomLG6ozf7s3CF2DhWFgzFnsHgyMCaxCST0jT/CU0AeriRBKxPViqWNXSf5DCebzg0wIBVF7URfi4DXAuxfvF33eHfE5/e003D5s1uMH2LLigifrYUrTklJQ5ebsnbPV6ZVy/4QKBgQDv8fWRAttHMAsg0a05ZXFRgBhib09ZUh0ZSDH0x3YaDdyPDpKYF67vjv06wFFGJkjhKUGsDN2nBPUYTAznKcglYTfn3iydlhv6OV/ZBwfaNiNaAG4lkuYMOb/6Wv5qNeB3bDMjlhDRT9wAjTT53A7XiQfzQeWAwzoq3Cj6r3JBPQKBgQDZZqY3on9HfGC3ZlLKSD3MOnONpTfjioPd08JBpAE5cw3UoJFE5P5eA0bZ/2qkGVgs/q5B0PdArRSPWNzSfXIafJCECktYPmwoGRv+XBwMkjwTFLjPoGhuJmdirjlJjIP+gjDz8LendLXFyI7dRboeF4LgfHoIserxuUmUJBC8RwKBgQDRxter9TRi05UXF1n8ET12RKiM/sX/0HOSU/UhDXWqp63KALKXeDVASeIJCHTGANi8ygYZdpIe4I2rtWmefH/4djubYznceI1zQdATfTsXQze7Cx9BiGHKFH9MUVuW3g2mOxmmph+D7+7nKI1FWWg8dhhWS6lr3sMvD5ZgPR2F/QKBgB6CLj9OeYghpzz1ihbDDpETftXY4r/210yRBAjMKDPUtpMpOVmuvReaZB4BnwiKWfpufyvTVG9qGqGHOe38FsAqzOkKvMoUcH8sDuaiLHmDKBURamIQw7b5graxdm6g3oEf6hjBpjREx6GK5KmeuGCysfYo4cNInIzxkKbObN7PAoGAc5gysCu/JVe8RgXAQ64eyR+UulJi8wqxYXJ63rTjMX6dCIzkbTuZrnVSKoYaNdy8zNjb/4+bHr5tiSVRS4oqTb3PHekKY8upLmJYBm1+/XwJT9rNvZd+lOBi9ht+yDcDUp/SlWqEmffnEJPR8LTekE1HCEPaV2e8FBO/B4nFhCw=
alipay.ras.private.key =MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDiQHDVZiRIviAd6VSPI7VeT/aEsjPeb2WF2es5OuNgqKmM48TDiAPeJCqFHZTqGq5evGihsli7Yen8NwpdELiF1NDvIR+SGBCqbV8eL2sLiJR0EahC0l2oHgQobOld7sSP5YUUbLpaJcQJlndgESyQ2u9E0B9XVgxcjY8tUgaqGORZw99viaAS9cbfQ1xDImSzTr4MDoi6Z9Crrrn1Gb7ygjRsWahBhMX7Ia21gjg93XvujPgJd5lzsNL3eZ9hxEuMdwYy9d5fc4aYYGqXj/bXnmtGU+E8zuY2uefZfw2+9grmzH+GWwmMNW0oIYcVDaz+yG/5ZP4VijaN0LlG+FdRAgMBAAECggEAVHlE55g0UeiSqzhT9wGZFPZ8Dz1Num4TFK+xcHO5M3ylmVHtRCgDcaxFJ+BMmj+N/RcRZdXl5UiAiUevmeHFU0qLG81dMTnE9yzQx79ikzLSYqe5EAHlMADNAp7vXr/oKeXDE0YpKcFR+VZxia+/2PG1RhcCrKQXB3NfEse+b0EaO6dwVjbvdfQY4PhI20/06Q4v/o+FG26yxZXvRuZiUlypyOREmpiiw17vTNcLAErOBAZcyOImBUMWOcKMqmhu8aQfpQPk0lpfueT8yuHDx5OhYFB5xi9Gk7ew/Xw2c2BVi337p05QZVgsAsxKjolem6Vaamy0KrqRu8MAYSu6xQKBgQD0ys4BlnuPshLJOGeEb/7azKLIrPOEeSU5rwVFdzduv7pvB/PTJUFYA2cGSlr4bTvszS7ZW11UmXT+/u6D0U1DWVCZhovTEZxYKAqOTMtm0NI4cwu2ayu8r0xYT28KS9/5T/rwo0G/1iHvCKim8nz4mDXW+6EV5IBnqpSOaD6y8wKBgQDsnFL4T3lTdp8PuCauXgF7WRXjTk7sVA1jJMmgt547ufkpYl4Yf7xTwoAhvBXficMWWIftyZ5zGgVN5i8+tRTp5oN+T7PwxPC9YZuKyvHw1yCju/E3AB7WrcTprg+YfPb8fRjQljkF4LbV5rjRH6BKuL5JhciGbZX/PZQ8p2u1qwKBgDB+aLcpz4qU9WHFecRjx3Ii7fChSpCoyzYVNQ8g4etfshhC1Au1Kq+75NH7MvBZ+3Aa6bgHgIK878+AQ1H7ybmY3P29CMAkkfto20Z7ciQJJEwohl559q0ncRFhkxbQFyu1q3m2bdUKH6jR509DZHx+8tOG/89td/6RbWKUxi7/AoGAWJVOGtjmO3E1q9Tt5mobc+quXyN6ONBfErc7JYiZHRNLTUsen11zTIiNIBQivEX/W+ZZPZU2VTFwuvFqzrdM1SUQJcIBRCr3Vm+spBHG8rwX5DUA4e6RnR4Bktsvy489iNns6GrVfnXa/cobd2+3u0HfO/dyU6HDfoO3c93aXXECgYEA2rMzOCqmLzYwL/xBulpn3G3i5b0Q4moSyGXuJSQRm58uKMfMDBfQKjjzDGgQ8AVqrVEH0FxbT/dsPt7FMPDf4j5OQbmlHeMC83s6dTo+DihpZfQ85VahQAdSLIIob3ZLONY3A0B2ltwpZPS6o8jw3c9acRvwlxNl8IGHqIVT1Tg=
#alipay.notify.parenturl =http://pay.21hourspushl.com/alipay/alipayOrderNotify
alipay.notify.url =http://vq6sh4.natappfree.cc/alipay/alipayOrderNotify
alipay.return.url
alipay.charset =UTF-8
#alipay.alipaypublic.key =MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi2ubzcqV10wYHSxmfBTvwCapzn2IEHttJ03OV1muCo3anE1IpOinfgQz0KaO0Ieg7z1nQLPgmesgW/yl12eaPRxmpOQsMvCmjN22Bg0GSr+8hT0RvoeLeARZFPxHuJRt4EnN+BrbNsUY919/uVnfiPdOdcgImCS6joanzCZ5fAYDXnSBojA0d0oQvwUhSq+j4XaQP37bhr0w91Eb8Z9lCwvMEiTb++xaGFLMhQ6sj6RlvLg4+JutrPyC+JcgQJfcDdpe21x3nCEhIiHe1zUGgWq2cO3v0iIOwud9U2iSeaHrpZw64lcazGMtcas5O/wYbTN7gYh1wbwyDaWxmMgMVQIDAQAB
#alipay.alipaypublic.key =MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAy8RPWs25NicpjK0q5DCqATnmkqrdgvC8jgPcajRwzwfpYlAOBVTCURmkVwHBXT7WJRSHsrmCoijPX7w+JtcAwR1VjrYjHAh9UTbQ9VQf5sniX+/J+tj23Otd2b4z4lDog61FXLc5wlu0y2COsbIWnLrIA13qPVyc7/8qsKkrmoRd0Juggc8y/tJ+ljuEnzssIgS4uqvLtRX5AUcsVCqAA0GV/3U35hmLL3fwVodBKyO8BAe9GCV34UZkcCv3yZZM+CVo4IJHsP3l7u75Abjmt/8TPT6Xu5yvrMAt5QUCSB/lu5TAu0O7jdXeV2OiBgatQyevgDx71NP2O5rzOGjj6wIDAQAB
alipay.alipaypublic.key =MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4kBw1WYkSL4gHelUjyO1Xk/2hLIz3m9lhdnrOTrjYKipjOPEw4gD3iQqhR2U6hquXrxoobJYu2Hp/DcKXRC4hdTQ7yEfkhgQqm1fHi9rC4iUdBGoQtJdqB4EKGzpXe7Ej+WFFGy6WiXECZZ3YBEskNrvRNAfV1YMXI2PLVIGqhjkWcPfb4mgEvXG30NcQyJks06+DA6IumfQq6659Rm+8oI0bFmoQYTF+yGttYI4Pd177oz4CXeZc7DS93mfYcRLjHcGMvXeX3OGmGBql4/2155rRlPhPM7mNrnn2X8NvvYK5sx/hlsJjDVtKCGHFQ2s/shv+WT+FYo2jdC5RvhXUQIDAQAB
alipay.public.key =
#����Ӧ�ù�Կ֤��·��
#alipay.certPath=D:\\Desktop\\zhifubao\\student\\appCertPublicKey1.crt
alipay.certPath=./home/docker/appCertPublicKey1.crt
#����֧������Կ֤��·��
#alipay.AlipayPublicCertPath=D:\\Desktop\\zhifubao\\student\\alipayCertPublicKey_RSA21.crt
alipay.AlipayPublicCertPath=./home/docker/alipayCertPublicKey_RSA21.crt 
#����֧������֤��·��
#alipay.RootCertPath= D:\\Desktop\\zhifubao\\student\\alipayRootCert1.crt
alipay.RootCertPath=./home/docker/alipayRootCert1.crt
alipay.payer.show.name =student
alipay.remark =ershiyipay
alipay.payee.type =ALIPAY_LOGONID

alipay.parentappid =2021002117682240
alipay.parentgateway =https://openapi.alipay.com/gateway.do
alipay.ras.private.parentkey =MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCLa5vNypXXTBgdLGZ8FO/AJqnOfYgQe20nTc5XWa4KjdqcTUik6Kd+BDPQpo7Qh6DvPWdAs+CZ6yBb/KXXZ5o9HGak5Cwy8KaM3bYGDQZKv7yFPRG+h4t4BFkU/Ee4lG3gSc34Gts2xRj3X3+5Wd+I9051yAiYJLqOhqfMJnl8BgNedIGiMDR3ShC/BSFKr6PhdpA/ftuGvTD3URvxn2ULC8wSJNv77FoYUsyFDqyPpGW8uDj4m62s/IL4lyBAl9wN2l7bXHecISEiId7XNQaBarZw7e/SIg7C531TaJJ5oeulnDriVxrMYy1xqzk7/BhtM3uBiHXBvDINpbGYyAxVAgMBAAECggEARe63GxWX7YNswQ1pZqn1zHNYT4wl+OaATOu5KZWBOCgJVMdrPdS5VvtypiE1l6HAduBc71aKvYn0FE/5O7/q3OZnEiSlivOtBxGa4RQdaNceD9MfGGvS6GN974nPy+Uf7BX5K48FEEbzC/oqDeXnu0MZZvjsXqxlq2Idvsg5vZxg3gCjie9OVC8Don5ukMtUvGcYn8gaSDVKSKagmOBHef7m0WL7YFAfqicQ3Gwf6kzGRjd7hfTafK8R5TGqEoMOUQAduw/W2EEUpAlUPTsXi8LeS+vRNferb7ujeUx4McHfMDs5YLQC9IfyLE+FhaufNTkus9ctqRIKYFA5r0Ub4QKBgQDoyC5VmN7TDHzg7I+RTGGc6so4240wxPK54RFZKZLABE6rs6g7ixJQaEemF9rmSxEDBIwhMsbPsIPC56bQ2pg8Jet6RBDjvWJloxp+dx7N1p5D24ygJFJ7N72ykHtICBFnqAkkTycNuft2ki6ZQyQpCbVgyN+s/1AjYSV2hiCiDQKBgQCZU4vlwdJXGkiM/QSEmzGJRk9ZnlxLKZYs/yTkU4Z6YSwvo2KCVvRINDVF2HPTDT1mG2ksMDTaXF74Dns07VxUM+uxwKSFGK1b9SqG/UqaJSFE40ktNoOs/3o6XYCanVh4EySSBBKr2xFOWLfJxis3UMyobl33IeJYvwfT2FepaQKBgCUIQ6bGbRxyLiOyPpzE4/qMt6MX+nw5uMutbI8cuAXoKYPTTv45/63fCRb5UI+2fXxXatuVMl+0GyIUrEspm3JmLfIDhhRU+qRksEBSPwpMDF2LPfH0FVMY6QrRRWuOLQaqitnF5dafMcwJMXScY9JLgxlkm4DwFRWrzMPwTpy5AoGAcSgOlEdCJBR6vMqyvecHXQdt4ncUKEiN07GNmZDnK4RxpsrPFeB0sqENO/nuKTGZQbUzHnCJYSpQ0INnfH086cvTw8Cn6q52quo6M5vVpgOHFR8kz2BvN4rouxBsrC85rox6LeUhnoGzuP2SzjAZjt5r3FZvtMbmFJcPgNImiBkCgYEAvy1VFxbaglsBszG9epqW/4w2n4fTDSC3amJwItQbEOhAieD56CI9jUlsUcTz1G2ta9UG1/rrv+m/p/s5L2/KKxvQrn8FLwA+cqIvQHdW5eKv8BCvgRSRfFPkhN1a623b0Eo4Kb5OwZKy761xf7BYLehlOSGO0dmHfJTBxSJ8MlQ=
#alipay.notify.parenturl =http://pay.21hourspushl.com/alipay/alipayOrderNotify
alipay.notify.parenturl =http://vq6sh4.natappfree.cc/alipay/alipayOrderNotify
alipay.return.parenturl
alipay.parentcharset =UTF-8
#alipay.alipaypublic.parentkey =MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi2ubzcqV10wYHSxmfBTvwCapzn2IEHttJ03OV1muCo3anE1IpOinfgQz0KaO0Ieg7z1nQLPgmesgW/yl12eaPRxmpOQsMvCmjN22Bg0GSr+8hT0RvoeLeARZFPxHuJRt4EnN+BrbNsUY919/uVnfiPdOdcgImCS6joanzCZ5fAYDXnSBojA0d0oQvwUhSq+j4XaQP37bhr0w91Eb8Z9lCwvMEiTb++xaGFLMhQ6sj6RlvLg4+JutrPyC+JcgQJfcDdpe21x3nCEhIiHe1zUGgWq2cO3v0iIOwud9U2iSeaHrpZw64lcazGMtcas5O/wYbTN7gYh1wbwyDaWxmMgMVQIDAQAB
                                
alipay.public.parentkey =
#����Ӧ�ù�Կ֤��·��

#alipay.certParentPath=D:\\Desktop\\zhifubao\\parent\\appCertPublicKey1.crt
alipay.certParentPath=./home/docker/appCertPublicKey.crt
#����֧������Կ֤��·��32
#alipay.AlipayParentPublicCertPath=D:\\Desktop\\zhifubao\\parent\\alipayCertPublicKey_RSA21.crt
alipay.AlipayParentPublicCertPath=./home/docker/alipayCertPublicKey_RSA2.crt
#����֧������֤��·��
#alipay.RootCertParentPath= D:\\Desktop\\zhifubao\\parent\\alipayRootCert1.crt
alipay.RootCertParentPath=./home/docker/alipayRootCert.crt 
alipay.payer.show.parentname =parent
alipay.parentremark =ershiyipay
alipay.payee.parenttype =ALIPAY_LOGONID








