<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>issue-inspect-service</artifactId>
        <groupId>com.ershiyi</groupId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>issue-inspect-service-api</artifactId>

    <dependencies>

        <dependency>
            <groupId>com.ershiyi</groupId>
            <artifactId>common-core</artifactId>
            <version>${platform.common.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.ershiyi</groupId>
            <artifactId>orm-starter</artifactId>
            <version>${platform.orm.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.ershiyi</groupId>
            <artifactId>web-starter</artifactId>
            <version>${platform.web.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.ershiyi</groupId>
            <artifactId>issue-inspect-domain</artifactId>
            <version>${platform.domain.issue-inspect.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.quartz-scheduler</groupId>
            <artifactId>quartz-jobs</artifactId>
            <version>2.2.1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-quartz</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ershiyi</groupId>
            <artifactId>student-app-domain</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
