#测试环境二十一小时配置 ==> 微信
#微信统一支付地址
wechat.unifiedorder.url=https://api.mch.weixin.qq.com/pay/unifiedorder
#公众号平台Appid
wechat.appid=
#公众号平台秘钥
wechat.appsecret=
#商户平台商户号
wechat.mchid=
#商户平台秘钥ID
wechat.wechatkey=
#body
wechat.body=JIAOYU
#微信支付类型
wechat.type=JSAPI
#获取授权用户信息地址
wechat.oatuh.getUserInfoUrl=http://xmcql.frpgz1.idcfengye.com/wechat/getUserInfo
#回调地址
wechat.notify.url=http://xmcql.frpgz1.idcfengye.com/wechat/whechatPayNotify
#微信重定向地址
wechat.redirect.url=http://gansu.xmcql.top


#支付宝测试环境配置
#支付宝网关
alipay.gateway=https://openapi.alipay.com/gateway.do
#商户appid
alipay.appid=2021001193605748
#私钥 pkcs8格式的
alipay.ras.private.key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC0ojWEKGWy6Zun04O6A9cdpj4UAo0viZu4fUlLGjOOiVtCyojfkgVlyWjEGQzhyxXIJVLEf3HNjrGJZTpBNIefOKbo2D7gZCKckvluLWOI6SPxq8fvyk3bdvipKDLhfjkMO4xdYbbtJmfVBmmXb++rDn5aWImAgP8UQtwwdMuS+20lPyKq0R7ERgilP59umtEychXHPhbUhmWf0WAqsEuoY3BFX+gTIC+G05QrB2co/enpa4bNTtSK5ZRlOQYEZbWkOmEv6XxkncePdgLh/y8Omx46FdO3pptZbD/6CRl2eL+opAy53XRTv5JNTvLvulRsYJH5L4I9TNQgpNB1jh95AgMBAAECggEBAKs9j4BfD7Jh1kdutFU26MrZ28X6eUAUs0RduYryJug8fQC/oqxX8LgDDUfB+71eWqLoByPzMb7ORK5dAbHpC509BrZ8snblVw6aIs55Rv/3DTVBRYSkg9THX4p1am7sy0Y2eaXZSaJeo1aHArkmy82dKtmZT5k8MRVTIQzq3EbUbfKKGT6in7UM8V5xVTRxAvtDxALYdiPQntcEO0fEg2j/Bnt3Z7Ep/qCr3NJAAN+ten2GmIyDht67quQn8fOgowlwhV3xuhCt9FcHh2nrT4o73fWs20P4rGVpYdHTgQj7mId6s3At55WRWSD0mxUh8/QKHoA/Ae9dDIMNMlBI6pECgYEA4iESU8GiVGGaLsTsobpIkjT7AbFesHqHHQiTw20oO2O2NtE3/2O1JCTE0k9MAMldYR9ZnyMxghz15PtvN3FB/p5K2tBGiKbpgTf8+8VC7pl0iEgKr0Vkth1DM8BGEKx8INe7Y5uvT98hfZVJpQkc9kTzzDXQUXU4WqbS41OW1CUCgYEAzH6hec7ZdnLrccvG1LklO3+57GxqtV5THZ/HKQNdqtuIeeh13xlECoLI0IbVtm902TmMcWYNb6A9oR2wL3tCT4u4dKyeYeqTb0Qi0EeKMc6hAgTOAvCAElhuhZjWA4RWCU4M41YbFyLiZTCtViJ0vE+GX/QPq0gCCCeSn0dbs8UCgYB9z+axgQd/KTqukNQTe2CLMD0DiRrk15c7GR2VWrNKr8SepTMhvej3rhlv5bykp2Rz+AxWFS+jc9d/ykDruPD96DY/nifQOgWq5mqz7eG6fNiwRlzjfZl2FbvhHDYfasg5Qa450lHs/3lTtO7fir15a421ba900uJC1ZR59HTznQKBgQCscwFzekeTBvicX29Ohs/qLB07TnZyepf2/H30jT0ZT8b4n1t/h4wEnSQCDiL9lWJhqZFRM/GSt/wg+atRb02NTVOBOOzbv/kTNM9y+1GEDS9kR27/tZcbYW3axfd8wcXYVPSzZjK0QRvQn8sdPzNYdmvoUSZBmBj2jYCtR30CzQKBgGhPgJigzuPiO2myyqdLBJAH6g9Bmfcw5Wl78UqYtLk1u5SmfeK748h/Yfa+w0YuDLPOfK22Kka/GQstBtSgZ8QJ+50Nj+QPQXTFdx4Piv3P5i4qV9DR/jqF6FWG/TGkcvFYedPKNzC/QQMOHvIIxzvBX16psMIfW1dSA8YxD9PI
#回调地址
alipay.notify.url=http://pay.21hourspushl.com/alipay/alipayOrderNotify
#支付成功跳转地址
alipay.return.url=
#字符编码格式
alipay.charset=UTF-8
#支付宝公钥
alipay.alipaypublic.key=GMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtKI1hChlsumbp9ODugPXHaY+FAKNL4mbuH1JSxozjolbQsqI35IFZcloxBkM4csVyCVSxH9xzY6xiWU6QTSHnzim6Ng+4GQinJL5bi1jiOkj8avH78pN23b4qSgy4X45DDuMXWG27SZn1QZpl2/vqw5+WliJgID/FELcMHTLkvttJT8iqtEexEYIpT+fbprRMnIVxz4W1IZln9FgKrBLqGNwRV/oEyAvhtOUKwdnKP3p6WuGzU7UiuWUZTkGBGW1pDphL+l8ZJ3Hj3YC4f8vDpseOhXTt6abWWw/+gkZdni/qKQMud10U7+STU7y77pUbGCR+S+CPUzUIKTQdY4feQIDAQAB
#支付宝公钥退款使用
alipay.public.key=

alipay.payer.show.name=二十一小时
alipay.remark=湖南二十一小时充值
alipay.payee.type=ALIPAY_LOGONID

spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime =30000 
spring.datasource.hikari.connection-test-query=SELECT 1





